### ISSUE TITLE
0.19.1 cannot run on java 8 due to UnsupportedClassVersionError

### ISSUE THREAD

**Issue by Elvis5566** [tminglei/slick-pg#487] opened 2020-07-31 06:15 UTC
Do we need to upgrade jre11 to use slick-pg?
thanks

> java.lang.UnsupportedClassVersionError: com/github/tminglei/slickpg/PgGeographyTypes$Geography has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by tminglei** [comment] 2020-08-01 12:24
Well, sorry! Wrongly transferred to java 11 when trying to resolve `not found: value getClass` because of scala/scala#8541.
I'll downgrade it and release a new version again.

**Comment by tminglei** [comment] 2020-08-01 14:53
@Elvis5566 resolved. Pls use `v0.19.2` instead.

**Closed by tminglei** 2020-08-01 14:53 UTC

**Comment by dhoepelman** [comment] 2020-09-09 14:54
Unfortunately we are getting this error when trying to upgrade from 0.19.0 to 0.19.2. 
Could it be that 0.19.2 is still compiled with JDK11?

```
$ sbt "dependencyList" | grep pg
[info] com.github.tminglei:slick-pg_2.13:0.19.2
[info] com.github.tminglei:slick-pg_core_2.13:0.19.2
[info] com.github.tminglei:slick-pg_jts_2.13:0.19.2
[info] com.github.tminglei:slick-pg_play-json_2.13:0.19.2
$ sbt test | grep java.lang.UnsupportedClassVersionError
java.lang.UnsupportedClassVersionError: com/github/tminglei/slickpg/PgGeographyTypes$Geography has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by dhoepelman** [comment] 2020-09-09 15:12
Yep, confirmed it by manually inspecting [the class file](https://en.wikipedia.org/wiki/Java_class_file#General_layout).
Note the header starts with `cafe babe 0000 0037`, the `0x37` byte corresponds to decimal 55 or JRE 11

```bash
$ wget https://repo1.maven.org/maven2/com/github/tminglei/slick-pg_jts_2.13/0.19.2/slick-pg_jts_2.13-0.19.2.jar
$ unzip slick-pg_jts_2.13-0.19.2.jar
$ cat com/github/tminglei/slickpg/PgGeographyTypes\$Geography.class | xxd | head -n 1
00000000: cafe babe 0000 0037 000c 0700 0707 000a  .......7........
```

**Comment by tminglei** [comment] 2020-09-10 01:49
@dhoepelman yeah, `slick-pg_jts` and `slick-pg_jts_lt` are still built for `Java 11`. Others look well.
I'll rebuild again.

**Comment by tminglei** [comment] 2020-09-10 03:00
@dhoepelman resolved. pls turn to use `v0.19.3`.

**Comment by dhoepelman** [comment] 2020-09-10 15:06
0.19.3 solves the problem, thanks!
