### ISSUE TITLE
Use pgjdbc support for primitive arrays

### ISSUE THREAD

**Issue by pettyjamesm** [tminglei/slick-pg#380] opened 2017-12-19 19:33 UTC
Just wanted to put https://github.com/pgjdbc/pgjdbc/pull/887 on your radar so that when it lands in a public release the slick-pg ArraySupport implementation can make use of it.

**Comment by tminglei** [comment] 2017-12-19 23:37
But we still need `SimpleArrayUtils. SimpleArray`. pgjdbc/pgjdbc#887 didn't cover `uuid[]`/`date[]`/`time[]`/`timestamp[]`/`decimal[]`.

Can you help point out the benefit?

**Comment by pettyjamesm** [comment] 2017-12-20 00:16
Our application has a fairly common pattern occuring which this would be really nice to have for. Currently, we have two choices of implementation for this kind of query:

**Compiled Array Queries**:
```scala
val compiledOnce = Compiled { (ids: ConstColumn[Seq[Long]]) =>
  Table.filter(_.id === ids.any)
}
```
Nice:
- is only compiled once by slick
- is only one query in the prepared statement cache

Unfortunate:
- is sent over the wire as a string instead of in the postgres binary representation
- performs a bunch of string concatenation inside the driver to generate a string value to pass to the server

**Dynamic Queries**
```scala
Table.filter(_.id.inSetBind(ids))
```
Nice:
- avoids extra CPU work and GC pressure required to generate the string array representation

Unfortunate:
- is recompiled by slick every time
- can generate a different entry in the prepared statement cache for each variation of `ids.length` used

I'm hoping that by supporting primitive array types directly we can get the good parts of both solutions. That said, once the pgjdbc version with primitive array support is published I can always just implement support myself. I just figured other people might have similar use cases to mine.

**Comment by tminglei** [comment] 2017-12-20 02:07
Oh yes, the binary representation is the major benefit.
Ok, let's use it when it's ready.

_Thanks! 👍_

**Comment by ploddi** [comment] 2018-01-17 12:17
Also current `fromString` uses scala parser combinators to tokenize and tend to be very slow compared to by-hand parser or other parsec libraries (parboiled, etc.).

**Comment by tminglei** [comment] 2018-01-17 12:40
@ploddi well, I'm not sure whether it can be smoothly moved to `parboiled`.
And where can I found the performance test result?

**Comment by ploddi** [comment] 2018-01-17 12:45
For example [this medium article](https://medium.com/@maciejb/a-csv-parser-moving-from-scala-parser-combinators-to-parboiled2-ebe96836e605) reports that Parboiled2-based parser is up to 500 times more performant than the Parser Combinators one.

**Comment by tminglei** [comment] 2018-01-18 02:30
@ploddi got it, thanks! I'll try to adjust it.

**Comment by pettyjamesm** [comment] 2018-01-18 06:30
Looks like 42.2.0 is just making its way to maven central now, primitive array support included. Didn't get a chance to read through the code, but the release notes mentioned some changes to default time zone handling that we might want to watch out for.

**Comment by tminglei** [comment] 2018-01-20 13:23
@pettyjamesm @ploddi updated to use primitive arrays. But moving to `parboiled2` will involve too many adjustments, won't do it by now.

**Comment by pettyjamesm** [comment] 2018-01-24 02:50
Any idea when a slick-pg version with primitive array support will make its way to maven? I'm ready to do a comparative benchmark in throughput against "IN (?, ...)" queries

**Comment by tminglei** [comment] 2018-01-24 09:20
@pettyjamesm just released in slick-pg v0.15.6. Pls check it.

**Closed by tminglei** 2018-01-24 09:20 UTC

**Comment by tminglei** [comment] 2018-01-28 12:50
@pettyjamesm pls use `v0.15.7` instead, since there is issue #385 in `v0.15.6`.

**Comment by apatzer** [comment] 2018-12-18 23:57
Could someone give a full example or test case of how to use the `.any` operator here, including imports? Could use some documentation on how to use `Compiled` matching `any` value in an array.

```
val compiledOnce = Compiled { (ids: ConstColumn[Seq[Long]]) =>
  Table.filter(_.id === ids.any) // <-- Error: `value any is not a member of ConstColumn[Seq[Long]]`
}
```

**Comment by apatzer** [comment] 2018-12-19 00:35
I think the issue is I would like to match a `Rep[Column]` against `ANY(ids)` rather a `Rep[Seq[Column]]`. The later works fine so long as `MyApi extends ArrayImplicits`

Ultimately the goal here is to have a compiled query that can take `ids: Seq[Long|UUID]` rather than having to compile the query each time (code profiling reveals that is fairly costly).
